### PR TITLE
#534: Fix Carousel swipeable with one child

### LINKED ISSUE #534: Infinite loop property with carousel that has only 1 slide, cause infinite loop on same slide on mobile devices
I found that if you have carousel with only 1 slide (e.g. db return only 1 value from carousel) and infinite loop property is `true`. The carousel on mobile devices will roll same slider on user slide action

Expected behavior: if infinite loop is on, but carousel has only 1 slide, the lib should disable behavior above on mobile devices

### PR DESCRIPTION
**Pull request by renancleyson-dev**
This fixes the Carousel being swipeable with the ```infiniteLoop``` flag on and with one child. The solution was to prevent the ```Swipe``` component to render when there are 1 or fewer children. (fixes #534)

### CODE REVIEW

File: src/components/Carousel.tsx [hunk 1]
```diff
@@ -803,6 +803,8 @@ export default class Carousel extends React.Component<Props, State> {
             return null;
         }
 
+        const swipeable = this.props.swipeable && Children.count(this.props.children) > 1;
```
Comment (leandrowd) [inline src/components/Carousel.tsx:806]: Please rename to `isSwipeable`

File: src/components/Carousel.tsx [hunk 2]
```diff
@@ -882,7 +884,7 @@ export default class Carousel extends React.Component<Props, State> {
                 <div className={klass.CAROUSEL(true)} style={{ width: this.props.width }}>
                     {this.props.renderArrowPrev(this.onClickPrev, hasPrev, this.props.labels.leftArrow)}
                     <div className={klass.WRAPPER(true, this.props.axis)} style={containerStyles}>
-                        {this.props.swipeable ? (
+                        {isSwipeable ? (
```
Comment (leandrowd) [inline src/components/Carousel.tsx:887]: I suspect you will need to do the same on the Thumbs component...

Comment (renancleyson-dev) [reply src/components/Carousel.tsx:887]: Agreed.

**Comment by leandrowd** [comment]
Published to npm as 3.2.12
