### PR TITLE
Remove thumb flickering, update images on change, and other fixes

### LINKED ISSUE #162: Thumbs in React Server Rendering
Hi.

I used this component in my project with Server Rendering, when showThumbs this errors appears:

`app.js:12 Cannot read property 'clientWidth' of undefined
TypeError: Cannot read property 'clientWidth' of undefined
    at t.n.updateSizes (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:2591)
    at t.value (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:4510)
    at t.value (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:3896)
    at S (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:18031)
    at v (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:18232)
    at Object.O (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:23193)
    at Object.a [as render] (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:2:685)
    at http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:12:2221
    at r (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:1835)
    at Generator._invoke (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:2955)`

Same to #29 but with thumbs.

Thanks!

### LINKED ISSUE #213: Thumbnails do not update with images when state changes.
I am polling an endpoint for new images using a setInterval() function. 

Every interval I set the state of a responses array. 

```javascript
 render(){
    return (
      <Carousel
        selectedItem={this.state.selectedItem}
        onClickThumb={this._onClickThumb.bind(this)}
      >
        {
          this.state.responses.map(function(url){
              return <img src={url} key={url} />
            }
          )
        }
      </Carousel>
    )
  }
}
```
When I get a new image, the image is present in  "ul.control-dots" but not in the thumbs.

The thumbs do not update along with the changing images. 

 Is there a way to refresh the thumbs when I add or remove images?

### LINKED ISSUE #226: Resizing window can make Thumbs enter incorrect state
Currently, if you make window smaller so the right arrow appears, then click it a few times, then make the window bigger again, the arrows disappear and you can no longer see the first few images.

Reproducible on the demos page.

Looks like updateSizes in Thumbs is not updating `this.state.firstItem` when the total visible items increases. It should compare `firstItem` to number of invisible items and not allow it to exceed it. So if there's 2 invisible items, `firstItem` should never exceed 2. If it does then it means desired space is not being used.

It would also be ABSOLUTELY brilliant if we can expose the updateSizes too. At the moment we are having to trigger a custom event for resize to get things to update (the carousel sits in a fairly flexible area with side bars popping in and out changing it's available size.)

### PR DESCRIPTION
**Pull request by driskell**
Hello!

This is a fairly big PR for which I apologise. To get it to work and clean I had to refactor thumbs a little.
Below are issues addressed in this PR and any relevant issue numbers:

1. Fix #226 Resizing window can make Thumbs enter incorrect state
    * updateSizes/getFirstItem combination now ensures that when we go from small width to big width, we update firstItem to be 0 so all thumbs display, whereas previously it would stay at say, 2, and mean there's two missing thumbnails and no arrows to access them
2. Similar to #226 but discovered after the initial fix. When moving from big to small width, the selected item could disappear behind the arrows.
    * updateSizes/getFirstItem combination now ensures selected item is always visible during resizes
3. Flickering of arrows whenever the carousel images are updated
    * updateSizes now uses setState so that it triggers a render exactly when things change. Before there was no setState so it was actually waiting for the carousel itself to cause a render and in my case made a flicker, presumedly because that render happened in a separate cycle.
4. Fix #213 Thumbnails not updating when images are updated.
    * Now we check children change on every prop update and update images state accordingly and visibility of items
5. There was no way to trigger a resize of thumbs to make arrows appear and disappear if the carousel changed size without the window resizing (we have it in a flex area so it flexes with other items)
    * Carousel updateSizes API now calls the same on the Thumbs component, so we can just call updateSizes on carousel now and everything updates cleanly.
6. Due to above changes, tests were failing due to clientWidth undefined on itemsWrapper. Seems tests did not test the updateSizes correctly due to no real DOM, but now that it's called within the rendering cycle it now picks it up
    * Simply check for itemsWrapper before allowing updateSizes, since it will calls it again anyway on any update to props after a render. This fixes tests.
    * This will likely also fix #162 server rendering though I am unable to confirm or guarantee there won't be further issues

Happy to consider tests but I'm completely alien to the type of tests happening or what kind of things best to test. Or would you say the existing tests cover most things already (since this is all minor fixes really)? I guess maybe a test for the firstItem stuff and the updateSizes call?

Thanks and hope this saves you some time :smile:

### CODE REVIEW

File: src/__tests__/__snapshots__/Carousel.js.snap [hunk 1]
```diff
@@ -204,17 +204,17 @@ exports[`Slider Snapshots center mode 1`] = `
         onTouchStart={[Function]}
         style={
           Object {
-            "MozTransform": "translate3d(NaNpx,0,0)",
```
Comment (driskell) [inline src/__tests__/__snapshots__/Carousel.js.snap]: This happened to be NaN before because updateSizes wasn't running in test. Now it is so the values are now 0s as expected so I updated snapshot (I think that's its name!) accordingly.

File: src/components/Carousel.js [hunk 2]
```diff
@@ -256,6 +256,10 @@ class Carousel extends Component {
             itemSize: itemSize,
             wrapperSize: isHorizontal ? itemSize * this.props.children.length : itemSize
         });
+
+        if (this.refs.thumbs) {
+            this.refs.thumbs.updateSizes();
```
Comment (driskell) [inline src/components/Carousel.js]: This is so `updateSizes` on Carousel triggers it for Thumbs too so everything updates nicely.

File: src/components/Thumbs.js [hunk 3]
```diff
@@ -26,81 +26,85 @@ class Thumbs extends Component {
...
+    componentWillReceiveProps(props, state) {
         if (props.selectedItem !== this.state.selectedItem) {
             this.setState({
                 selectedItem: props.selectedItem,
                 firstItem: this.getFirstItem(props.selectedItem)
             });
         }
+        if (props.children !== this.props.children) {
+            this.setState({
+               images: this.getImages()
```
Comment (driskell) [inline src/components/Thumbs.js]: This ensures thumbs update when we give new images.

File: src/components/Thumbs.js [hunk 4]
```diff
@@ -26,81 +26,85 @@ class Thumbs extends Component {
...
     componentDidUpdate(prevProps) {
-        if (!prevProps.children && this.props.children && !this.state.initialized) {
-            this.setupThumbs();
+        if (this.props.children === prevProps.children) {
+            return;
         }
+
+        // This will capture any size changes for arrow adjustments etc.
+        // usually in the same render cycle so we don't see any flickers
+        this.updateSizes();
```
Comment (driskell) [inline src/components/Thumbs.js]: When thumbs updated, re-calculate sizes, this one is AFTER render as it needs itemsWrapper clientWidth.

File: src/components/Thumbs.js [hunk 5]
```diff
@@ -26,81 +26,85 @@ class Thumbs extends Component {
...
-    destroyThumbs () {
+    destroyThumbs() {
         // removing listeners
         window.removeEventListener("resize", this.updateSizes);
         window.removeEventListener("DOMContentLoaded", this.updateSizes);
     }
 
     updateSizes = () => {
-        if (!this.state.initialized) {
+        if (!this.props.children || !this.refs.itemsWrapper) {
```
Comment (driskell) [inline src/components/Thumbs.js]: Maybe it clearer if this checks `this.state.images` but I thought it be OK and I'll await your thoughts on other things :smile:

File: src/components/Thumbs.js [hunk 6]
```diff
@@ -26,81 +26,85 @@ class Thumbs extends Component {
...
             selectedItem: props.selectedItem,
             hasMount: false,
-            firstItem: this.getFirstItem(props.selectedItem),
-            images: []
+            firstItem: 0,
+            itemSize: null,
+            visibleItems: 0,
+            lastPosition: 0,
+            showArrows: false,
+            images: this.getImages()
```
Comment (driskell) [inline src/components/Thumbs.js]: Everything state is in `state` now so the relevant setState calls ensure we properly render immediately rather than waiting for a side-effect somewhere else to do it, and causing flickering etc.

File: src/__tests__/__snapshots__/Carousel.js.snap (hunk 1 above)
Comment (leandrowd) [reply src/__tests__/__snapshots__/Carousel.js.snap]: How did you update the snapshot?

File: src/components/Thumbs.js [hunk 7]
```diff
@@ -26,81 +26,85 @@ class Thumbs extends Component {
...
-        this.itemSize = this.props.thumbWidth ? this.props.thumbWidth : outerWidth(this.refs.thumb0);
-        this.visibleItems = Math.floor(this.wrapperSize / this.itemSize);
-        this.lastPosition = total - this.visibleItems;
-        this.showArrows = this.visibleItems < total;
+        const wrapperSize = this.refs.itemsWrapper.clientWidth;
+        const itemSize = this.props.thumbWidth ? this.props.thumbWidth : outerWidth(this.refs.thumb0);
+        const visibleItems = Math.floor(wrapperSize / itemSize);
+        const lastPosition = total - visibleItems;
+        const showArrows = visibleItems < total;
+        this.setState({
```
Comment (leandrowd) [inline src/components/Thumbs.js]: Which version of React did you test this with? React 16?

**Comment by leandrowd** [comment]
Awesome work @driskell!

Just as a sanity check:
1) What browsers did you test?
2) Which version of React?

Please, if possible, keep an eye on the issues after we merge as I'm not actively looking...

Thanks for the help!

File: src/__tests__/__snapshots__/Carousel.js.snap (hunk 1 above)
Comment (driskell) [reply src/__tests__/__snapshots__/Carousel.js.snap]: Likely the wrong way. It looked generated but I wasn't sure how to update it and was worried doing so might yank in other things and make tests pass that should fail. So I just inspected the test failure message and applied the patch manually as I considered it to be expected and correct.

Happy to revisit if needed.

**Comment by driskell** [comment]
I can't remember so I will double down on further tests. I will test Safari, Chrome, Firefox and iOS as those I have freely available.

React was version 16.2.

I have subscribed to issues already :)

File: src/__tests__/__snapshots__/Carousel.js.snap (hunk 1 above)
Comment (leandrowd) [reply src/__tests__/__snapshots__/Carousel.js.snap]: Well, tests are passing so you did well. To make sure there is nothing wrong, run `yarn update-snapshots`. If everything is correct you won't have anything to commit after that.

**Comment by leandrowd** [comment]
Fair enough, who needs IE, right? Keeping an eye on issues is enough after covering those browsers. Thanks again for the great work! Let me know when you think it's safe to merge.

**Comment by leandrowd** [comment]
Any update here? Should I merge or you are still testing/working on it?

**Comment by driskell** [comment]
Just doing some testing now.

Tested fine so far in Chrome latest, Firefox latest, Safari OS X latest.
Just going to attempt some iOS and IE11/Edge but might struggle as I'm on a slow connection. I would guess they're OK though.

File: src/__tests__/__snapshots__/Carousel.js.snap (hunk 1 above)
Comment (driskell) [reply src/__tests__/__snapshots__/Carousel.js.snap]: Ran `yarn update-snapshots`. All tests passed and no changes reported :smile:

**Comment by driskell** [comment]
Tested iOS Safari latest and all working great, switching from landscape to portrait working nicely.

**Comment by driskell** [comment]
OK I can't manage to get an IE testing connection due to poor internet. I'll try to get one sorted in next few days perhaps. Though I expect compatibility should be fine since the entire change it's mostly logical and nothing new. Happy to merge if you area and I can double check things when I can.

**Comment by leandrowd** [comment]
I trust you.

**Comment by driskell** [comment]
OK had a better connection. IE 11 is fine. IE Edge 16 is also fine. All tested on BrowserStack real devices. Also tested and it's fine on Galaxy S8 Chrome and iPad Air 2 (iOS 8). :+1:
